### ISSUE TITLE
Mod perhaps not working in multiplayer?

### ISSUE THREAD

**Issue by whitedude877** [RileSamurott/Providirector#1]
4 player game, running 140 other mods granted, had to enable debug mode to get it to work. 

The game runs for about 5 seconds before all players freeze from the host's perspective, their games continue but everyone else is frozen for each of them. Game eventually ends on its own before returning to the lobby. The lobby is completely broken as far as UI is concerned and completely dark. The host must rehost the lobby for anyone to speak to each other. 
https://www.mediafire.com/file/dp43zlx503tzblr/providirectorlog.txt/file

Also a suggested feature: A random player is selected to be the director.

**Comment by ikesicle** [comment]
Thanks for the bug report. I haven't had the time to test the mod against other mods running concurrently; I'll try to eventually get around to making the game stable enough to work with other mods. Thanks for posting the logfiles too - might make this a standard for future bug reports if there's eventually too many to handle. 

As for selecting a random player to be the director, that's a bit tricky because the director requires server-level permissions for many of the things it does. With the knowledge I have right now I probably wouldn't be able to make it - though you could definitely make a Pull Request if you find a method which works.
