### ISSUE TITLE
List of issues after playing

### ISSUE THREAD

**Issue by CrystalCulture** [RileSamurott/Providirector#2]
found several things having played for a bit:

---had a bug where all enemies were invisible and the menu UI broke afterwards, happened all but one time, no idea why
![20230511163930_1](https://github.com/RileSamurott/Providirector/assets/127253576/cfd66cb4-2b4e-423a-8acd-5cab35ac76ce)
![20230511163743_1](https://github.com/RileSamurott/Providirector/assets/127253576/ca4fb9e2-5717-48c2-83c0-089ad8246620)
---going to the lunar freezes the game, requiring you to quit to menu

suggestion to possibly fix issues:
make the director its own character, and put them on the enemy team

**Comment by ikesicle** [comment]
Hi, thanks for leaving the bug report!

I'm not sure what could cause the invisible enemies, but part of me suspects that since it didn't happen once it probably has something to do with variables in the code not being properly reset - I'll look into it. Could you post the log contents of that game, if you still have them on hand?

As for making the director its own character, that was actually how the mod originally worked, to an extent (random wisp without a hitbox). I could try to reimplement that, as it seems like a lot of the compatibility issues for this mod also come from the unorthodox nature of having a player without a body.

Edit: Also what do you mean by Lunar? Do you mean the bazaar, or just Commencement?

**Comment by CrystalCulture** [comment]
so following up as of the latest update:

by lunar I meant bazaar, which we only got to once (never made it past stage 1)

and as of the latest update, there are two issues:
1. the invisible soul wisp still has a hitbox
2. the non-director characters are also able to cycle perspectives with M1/M2 (but still have full control of themselves)

**Comment by CrystalCulture** [comment]
the enemy bug is fixed, however.

**Comment by CrystalCulture** [comment]
update: this issue only occurs when someone joins while you're on the character select screen, joining from the lobby screen does not have this issue

**Comment by CrystalCulture** [comment]
attempting to play with three people makes this issue occur regardless

**Comment by CrystalCulture** [comment]
I stand corrected, it working was a one-time thing, it does not work anymore.

**Comment by ikesicle** [comment]
Should be working now as of the lastest update, director now has its own "player" character, no problems found during testing. Sorry for getting back so late; I was busy with school for almost the entirety of June.

If there are still issues, contact me ASAP by reopening this issue.
