### ISSUE TITLE
Voidling bug

### ISSUE THREAD

**Issue by pineapple1661** [RileSamurott/Providirector#9]
Cutscene for voidling didn't show for the 2 other players in the lobby, host saw it but did not take control of the voidling.

**Screenshots**
Didn't take any.

**Enabled Mods**
BepInEx_GUI by RiskofThunder

FixPluginTypesSerialization by RiskofThunder

RoR2BepInExPack by RiskofThunder

BepInExPack by bbepis

HookGenPatcher by RiskofThunder

R2API_Core by RiskofThunder

R2API_Skins by RiskofThunder

R2API_Addressables by RiskofThunder

R2API_SceneAsset by RiskofThunder

R2API_Elites by RiskofThunder

R2API_Items by RiskofThunder

R2API_Loadout by RiskofThunder

R2API_Prefab by RiskofThunder

R2API_Sound by RiskofThunder

R2API_TempVisualEffect by RiskofThunder

R2API_Unlockable by RiskofThunder

R2API_Director by RiskofThunder

R2API_ArtifactCode by RiskofThunder

R2API_CommandHelper by RiskofThunder

R2API_Deployable by RiskofThunder

R2API_Dot by RiskofThunder

R2API_Language by RiskofThunder

R2API_LobbyConfig by RiskofThunder

R2API_Orb by RiskofThunder

R2API_Difficulty by RiskofThunder

R2API_DamageType by RiskofThunder

R2API_RecalculateStats by RiskofThunder

R2API_Networking by RiskofThunder

R2API_ContentManagement by RiskofThunder

R2API by tristanmcpherson

Risk_Of_Options by Rune580

Providirector by SaugaWorkshop

BetterUI by XoXFaby

ItemStats by Moffein

ProperSave by KingEnderBrine

**Suggestions**
Keep the art style of the enemy icons, it's hilarious.

**Comment by ikesicle** [comment]
The first part is NOT supposed to happen, everyone is supposed to see the Voidling cutscene. I'll see what I can do about it, because I did mess with some of the area-based triggers which cause stuff like the Voidling cutscene to occur. It may also be possible that it was a one-off occurrence, so I'll do some testing when I can find time in between Uni schoolwork.

As for the not taking control part, that is intentional; I deemed controlling Voidling to be far too janky and uninteresting. Most of the time you can't see where you're shooting because his model is just so damn big.

As for the icons, thank you!!!

**Comment by ikesicle** [comment]
Fixed in the latest update, turns out it was because of some authority-related shenanigans client-side. Should be fixed in Version 1.0.1
